services:
  - type: web
    name: my-flask-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      ./setup.sh
    startCommand: gunicorn -w 2 -b 0.0.0.0:8000 app:app
    port: 8000
